---   ##### Example for Conditions
- hosts: webservers
  remote_user: ansibleadmin
  become: yes
  gather_facts: yes
  tasks:
   - name: create a file  with hostname 
     file: 
       path: /tmp/{{ ansible_hostname  }}
       state: touch
#     when: ( ansible_os_family == "RedHat" and ansible_major_version == "6" or ansible_major_version == "7")

     when: ( ansible_os_family == "RedHat" and ansible_distribution_major_version >= "6") 

