---
### Other Playbook
- hosts: server2
  remote_user: ansibleadmin
  become: yes
  gather_facts: yes
  tasks: 
    - name: Inatlling webserver
      yum: 
        name: httpd 
        state: present

    - name: copy index.html 
      copy: 
        src: index.html  
        dest: /var/www/html/index.html

    - name: start the httpd service
      service: 
        name: httpd 
        state: started 
        enabled: yes
